// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreDbTest
{

    // JobQueue
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class HangFire_JobQueueConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HangFire_JobQueue>
    {
        public HangFire_JobQueueConfiguration()
            : this("HangFire")
        {
        }

        public HangFire_JobQueueConfiguration(string schema)
        {
            Property(x => x.FetchedAt).IsOptional();
        }
    }

}
// </auto-generated>
