// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreDbTest
{

    // Server
    [Table("Server", Schema = "HangFire")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class HangFire_Server
    {

        ///<summary>
        /// Id (Primary key) (length: 100)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "nvarchar")]
        [Index(@"PK_HangFire_Server", 1, IsUnique = true, IsClustered = true)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Key]
        [Display(Name = "Id")]
        public string Id { get; set; }

        ///<summary>
        /// Data
        ///</summary>
        [Column(@"Data", Order = 2, TypeName = "nvarchar(max)")]
        [Display(Name = "Data")]
        public string Data { get; set; }

        ///<summary>
        /// LastHeartbeat
        ///</summary>
        [Column(@"LastHeartbeat", Order = 3, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Last heartbeat")]
        public System.DateTime LastHeartbeat { get; set; }
    }

}
// </auto-generated>
