// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreDbTest
{

    public interface IMyDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<HangFire_AggregatedCounter> HangFire_AggregatedCounters { get; set; } // AggregatedCounter
        System.Data.Entity.DbSet<HangFire_Counter> HangFire_Counters { get; set; } // Counter
        System.Data.Entity.DbSet<HangFire_Hash> HangFire_Hashes { get; set; } // Hash
        System.Data.Entity.DbSet<HangFire_Job> HangFire_Jobs { get; set; } // Job
        System.Data.Entity.DbSet<HangFire_JobParameter> HangFire_JobParameters { get; set; } // JobParameter
        System.Data.Entity.DbSet<HangFire_JobQueue> HangFire_JobQueues { get; set; } // JobQueue
        System.Data.Entity.DbSet<HangFire_List> HangFire_Lists { get; set; } // List
        System.Data.Entity.DbSet<HangFire_Schema> HangFire_Schemata { get; set; } // Schema
        System.Data.Entity.DbSet<HangFire_Server> HangFire_Servers { get; set; } // Server
        System.Data.Entity.DbSet<HangFire_Set> HangFire_Sets { get; set; } // Set
        System.Data.Entity.DbSet<HangFire_State> HangFire_States { get; set; } // State
        System.Data.Entity.DbSet<JobParamView> JobParamViews { get; set; } // JobParamView
        System.Data.Entity.DbSet<MyTable> MyTables { get; set; } // MyTable
        System.Data.Entity.DbSet<View2> View2 { get; set; } // View2

        int SaveChanges();
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<MyOwnProcReturnModel> MyOwnProc(int? param1, string param2, out string nvarParam, decimal? dec);
        System.Collections.Generic.List<MyOwnProcReturnModel> MyOwnProc(int? param1, string param2, out string nvarParam, decimal? dec, out int procResult);

    }

}
// </auto-generated>
