// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreDbTest
{

    // MyTable
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MyTableConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MyTable>
    {
        public MyTableConfiguration()
            : this("dbo")
        {
        }

        public MyTableConfiguration(string schema)
        {
            Property(x => x.MyId).IsFixedLength();
            Property(x => x.MyTable_).IsOptional().IsUnicode(false);
            Property(x => x.Str1).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Str2).IsOptional();
            Property(x => x.Dec1).IsOptional().HasPrecision(18,4);
            Property(x => x.Varcharmax).IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
