// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreDbTest
{

    // View2
    [Table("View2", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class View2
    {

        ///<summary>
        /// Id (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        ///<summary>
        /// StateId
        ///</summary>
        [Column(@"StateId", Order = 2, TypeName = "int")]
        [Display(Name = "State ID")]
        public int? StateId { get; set; }

        ///<summary>
        /// StateName (length: 20)
        ///</summary>
        [Column(@"StateName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "State name")]
        public string StateName { get; set; }

        ///<summary>
        /// InvocationData (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"InvocationData", Order = 4, TypeName = "nvarchar(max)")]
        [Required(AllowEmptyStrings = true)]
        [Key]
        [Display(Name = "Invocation data")]
        public string InvocationData { get; set; }

        ///<summary>
        /// Arguments (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Arguments", Order = 5, TypeName = "nvarchar(max)")]
        [Required(AllowEmptyStrings = true)]
        [Key]
        [Display(Name = "Arguments")]
        public string Arguments { get; set; }

        ///<summary>
        /// CreatedAt (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CreatedAt", Order = 6, TypeName = "datetime")]
        [Required]
        [Key]
        [DataType(DataType.DateTime)]
        [Display(Name = "Created at")]
        public System.DateTime CreatedAt { get; set; }

        ///<summary>
        /// ExpireAt
        ///</summary>
        [Column(@"ExpireAt", Order = 7, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Expire at")]
        public System.DateTime? ExpireAt { get; set; }

        ///<summary>
        /// Expr1 (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Expr1", Order = 8, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Expr 1")]
        public int Expr1 { get; set; }

        ///<summary>
        /// JobId (Primary key)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"JobId", Order = 9, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Job ID")]
        public int JobId { get; set; }

        ///<summary>
        /// Name (Primary key) (length: 40)
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Name", Order = 10, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(40)]
        [StringLength(40)]
        [Key]
        [Display(Name = "Name")]
        public string Name { get; set; }

        ///<summary>
        /// Value
        ///</summary>
        [Column(@"Value", Order = 11, TypeName = "nvarchar(max)")]
        [Display(Name = "Value")]
        public string Value { get; set; }
    }

}
// </auto-generated>
